# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('subject', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=2000)),
                ('pic', models.ImageField(default='static/img/no-image.png', upload_to='static/img/')),
            ],
        ),
    ]
