# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='subject',
            field=models.TextField(),
        ),
    ]
