# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 09:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20160906_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 6, 9, 59, 38, 116488)),
        ),
    ]
