# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 10:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_blogpost_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 6, 10, 12, 0, 906299, tzinfo=utc)),
        ),
    ]
