# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 10:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20160906_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2016, 9, 6, 10, 13, 24, 348386, tzinfo=utc)),
        ),
    ]
